bugfix: build-wp-rocket.yaml

diff --git a/.github/workflows/build-wp-rocket.yaml b/.github/workflows/build-wp-rocket.yaml
--- a/.github/workflows/build-wp-rocket.yaml
+++ b/.github/workflows/build-wp-rocket.yaml
@@ -31,8 +31,10 @@ jobs:
           echo "UPSTREAM_RELEASE=$(curl -f -sSL "https://api.github.com/repos/wp-media/wp-rocket/releases/latest" 2>/dev/null|awk -F'"' '/"name":/{print $4}')" >> $GITHUB_ENV
 
       - name: Check upstream release
-        if: ! ${{ env.UPSTREAM_RELEASE }}
-        run: { echo "__ERROR: FAILED get '${UPSTREAM_RELEASE}' release"; exit 2; }
+        if: "${{ env.UPSTREAM_RELEASE == '' }}"
+        run: |
+          echo "__ERROR: FAILED get '${UPSTREAM_RELEASE}' release"
+          exit 2
 
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
